name: Coverage Reporting

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8.15.1'

jobs:
  coverage:
    name: 📊 Coverage Report
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: timescale/timescaledb:latest-pg15
        env:
          POSTGRES_DB: moneywise_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U postgres -d moneywise_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🧪 Run tests with coverage
        run: pnpm test:ci
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: password
          DB_NAME: moneywise_test
          REDIS_URL: redis://localhost:6379
          NODE_ENV: test

      - name: 📊 Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage-reports/lcov/lcov.info
            apps/backend/coverage/lcov.info
            apps/web/coverage/lcov.info
          flags: unittests
          name: moneywise-coverage
          fail_ci_if_error: false
          verbose: true

      - name: 📊 Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-reports/
          retention-days: 30

      - name: 📊 Comment coverage report on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: coverage-reports/text-summary/index.txt

      - name: 🚦 Coverage threshold check
        run: |
          echo "📊 Checking coverage thresholds..."
          
          # Extract overall coverage from the summary
          if [ -f "coverage-reports/text-summary/index.txt" ]; then
            echo "📋 Coverage Summary:"
            cat coverage-reports/text-summary/index.txt
            
            # Parse overall coverage percentage
            OVERALL_COVERAGE=$(grep -o 'All files.*[0-9]\+\.[0-9]\+%' coverage-reports/text-summary/index.txt | grep -o '[0-9]\+\.[0-9]\+' | head -1 || echo "0")
            
            echo "🎯 Overall Coverage: ${OVERALL_COVERAGE}%"
            
            # Check if coverage meets 80% threshold
            if [ "$(echo "$OVERALL_COVERAGE >= 80" | bc -l 2>/dev/null || echo "0")" -eq 1 ]; then
              echo "✅ Coverage threshold met (${OVERALL_COVERAGE}% >= 80%)"
            else
              echo "⚠️ Coverage below threshold (${OVERALL_COVERAGE}% < 80%)"
              echo "📋 This is a warning - coverage will be tracked but not enforced during CI/CD setup phase"
            fi
          else
            echo "⚠️ Coverage summary not found - this may indicate a test execution issue"
          fi

  coverage-badges:
    name: 📈 Update Coverage Badges
    runs-on: ubuntu-latest
    needs: coverage
    if: github.ref == 'refs/heads/main'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📈 Generate coverage badges
        run: |
          echo "📈 Coverage badges will be generated by Codecov"
          echo "Visit: https://codecov.io/gh/${{ github.repository }}"
          echo "Badge URL: https://codecov.io/gh/${{ github.repository }}/branch/main/graph/badge.svg"