-- Migration: Restore category depth column
-- 
-- CONTEXT: The depth column was accidentally dropped in migration 20251128021358_add_banking_customer_v6
-- This migration restores it along with the trigger for automatic depth calculation.
--
-- WHY THIS HAPPENED:
-- 1. Migration 20251022000004 added the depth column with a PostgreSQL trigger
-- 2. Migration 20251128021358 (auto-generated by Prisma) dropped it as a side effect
-- 3. The Prisma schema was updated to re-add depth, but no migration was created
-- 4. CI/CD runs migrations, so the column was missing in CI database
--
-- FIX: This migration re-adds the column and trigger

-- Add depth column back to categories
ALTER TABLE "categories" ADD COLUMN IF NOT EXISTS "depth" INTEGER NOT NULL DEFAULT 0;

-- Add check constraint to limit hierarchy depth (if not exists)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'chk_category_depth'
    ) THEN
        ALTER TABLE "categories" ADD CONSTRAINT "chk_category_depth" CHECK (depth <= 3);
    END IF;
END $$;

-- Recreate trigger function to maintain depth and prevent cycles
CREATE OR REPLACE FUNCTION update_category_depth()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.parent_id IS NULL THEN
    NEW.depth := 0;
  ELSE
    SELECT depth + 1 INTO NEW.depth
    FROM categories
    WHERE id = NEW.parent_id;
    
    -- Check for circular references using CTE
    WITH RECURSIVE ancestors AS (
        SELECT id, parent_id, 1 as depth
        FROM categories
        WHERE id = NEW.parent_id
        UNION ALL
        SELECT c.id, c.parent_id, a.depth + 1
        FROM categories c
        JOIN ancestors a ON c.id = a.parent_id
        WHERE a.depth < 10
    )
    SELECT COUNT(*) INTO NEW.depth
    FROM ancestors
    WHERE id = NEW.id;
    
    IF NEW.depth > 0 THEN
      RAISE EXCEPTION 'Circular reference detected in category hierarchy';
    END IF;
    
    -- Recalculate actual depth
    SELECT depth + 1 INTO NEW.depth
    FROM categories
    WHERE id = NEW.parent_id;
    
    IF NEW.depth > 3 THEN
      RAISE EXCEPTION 'Category hierarchy depth cannot exceed 3 levels';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Recreate trigger
DROP TRIGGER IF EXISTS trg_category_depth ON categories;
CREATE TRIGGER trg_category_depth
BEFORE INSERT OR UPDATE ON categories
FOR EACH ROW EXECUTE FUNCTION update_category_depth();

-- Add comment
COMMENT ON COLUMN categories.depth IS 'Hierarchy depth for circular reference prevention. Max depth: 3 levels. Managed by trg_category_depth trigger.';
